class_name MapRuntimeResource

extends Resource

## Runtime map data format
## This is the optimized format used by the Match scene at runtime
## Converted from MapResource during export

@export var size: Vector2i = Vector2i(50, 50)

# Navigation data (baked from collision grid)
@export var navigation_mesh_data: Dictionary = {}

# Merged collision shapes (boxes, walls, slopes) with group identifiers
@export var collision_shapes: Array[Dictionary] = []

# Runtime entity spawns (converted from editor placements)
@export var entity_spawns: Array[Dictionary] = []

# Visual data (optional, for cosmetic rendering)
@export var placed_textures: Array[Dictionary] = []


func instantiate_runtime() -> Node3D:
	"""Create a runtime map instance that can be used by Match"""
	# This will be implemented to create the actual map node
	# For now, return a placeholder
	var map_instance: Node3D = Node3D.new()
	map_instance.name = "RuntimeMap"
	return map_instance


static func from_editor_map(editor_map: MapResource) -> MapRuntimeResource:
	"""Convert an editor MapResource to runtime format"""
	var runtime_map: MapRuntimeResource = MapRuntimeResource.new()
	runtime_map.size = editor_map.size

	# Copy entity spawns
	runtime_map.entity_spawns = editor_map.placed_entities.duplicate(true)

	# Copy merged collision shapes (generated by CollisionShapeBuilder)
	runtime_map.collision_shapes = editor_map.collision_shapes.duplicate(true)

	# Navigation baking would happen here in a full implementation
	# For now, we'll just store the collision grid data
	runtime_map.navigation_mesh_data = {
		"collision_grid": editor_map.collision_grid, "size": editor_map.size
	}

	return runtime_map


func validate() -> Array[String]:
	"""Validate runtime map data"""
	var errors: Array[String] = []

	if size.x < 10 or size.y < 10:
		errors.append("Map size is too small")

	return errors
